const API=window.location.protocol==='file:'||window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://127.0.0.1:4174':window.location.protocol+'//'+window.location.hostname+':4174';
function init(){const q=document.querySelector('.queue:not(.current-queue)');if(!q||q.dataset.enhanced)return;q.dataset.enhanced='1';const head=q.querySelector('.queue-head');const controls=document.createElement('div');controls.className='admin-controls';controls.innerHTML='<input aria-label="Поиск по артикулу" placeholder="Поиск артикула"><select aria-label="Маркетплейс"><option value="ALL">Все маркетплейсы</option><option value="WB">WB</option><option value="OZON">Ozon</option></select><select aria-label="Статус"><option value="ALL">Все статусы</option><option>Ожидает</option><option>В печати</option><option>Забрано</option><option>Напечатано</option><option>Ошибка</option></select><button type="button">Отчёт</button><button type="button">Настройки</button>';head.append(controls);const [search,market,status,report,settings]=controls.children;const filter=()=>{const text=search.value.toUpperCase(),m=market.value,s=status.value;[...q.querySelectorAll('.tr:not(.th)')].forEach(row=>{const value=row.textContent.toUpperCase();const ok=value.includes(text)&&(m==='ALL'||row.children[1]?.textContent.trim()===m)&&(s==='ALL'||row.children[3]?.textContent.trim()===s);row.style.display=ok?'':'none'})};[search,market,status].forEach(x=>x.addEventListener('input',filter));report.onclick=async()=>{const d=await fetch(API+'/api/report').then(x=>x.json());alertBox('Отчёт',`Всего: ${d.total} шт. · WB: ${d.wb} · Ozon: ${d.ozon} · В работе: ${d.waiting} · Забрано: ${d.taken} · Напечатано: ${d.done}`)};settings.onclick=async()=>{const d=await fetch(API+'/api/settings').then(x=>x.json());alertBox('Настройки',`База макетов: ${d.base}\nПечать: ${d.print}\nТаблица расширений: ${d.map}\nДопустимые файлы: ${d.allowed.join(', ')}`)}}
function initStepper(){const i=document.querySelector('.row input[type="number"]');if(!i||i.parentElement.dataset.stepper)return;i.parentElement.dataset.stepper='1';const wrap=i.parentElement;const mk=(text,delta)=>{const b=document.createElement('button');b.type='button';b.className='stepper-btn';b.textContent=text;b.onclick=()=>{i.value=Math.max(1,Number(i.value||1)+delta);i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))};return b};wrap.classList.add('stepper');wrap.insertBefore(mk('−',-1),i);wrap.append(mk('+',1))}
function alertBox(title,text){const old=document.querySelector('.app-dialog');if(old)old.remove();const d=document.createElement('div');d.className='app-dialog';d.innerHTML=`<div class="app-dialog-card"><b>${title}</b><p>${text.replaceAll('\n','<br>')}</p><button type="button">Закрыть</button></div>`;d.querySelector('button').onclick=()=>d.remove();document.body.append(d)}
function restrictAdminControls(){if(window.printflowUser?.role==='admin')return;document.querySelectorAll('.admin-controls button').forEach(button=>{if(button.textContent.trim()==='Настройки')button.remove()})}
function updateHistoryCount(q){const total=[...q.querySelectorAll('.table .tr:not(.th)')].filter(row=>row.style.display!=='none').reduce((sum,row)=>sum+(Number.parseInt((row.children[2]?.textContent||'').replace(/\s/g,''),10)||0),0);const count=q.querySelector('.history-controls strong'),value=`Всего: ${total} шт.`;if(count&&count.textContent!==value)count.textContent=value}
function initHistoryCount(){const q=document.querySelector('.queue:not(.current-queue)');if(!q||q.dataset.historyCountReady)return;q.dataset.historyCountReady='1';q.addEventListener('input',()=>updateHistoryCount(q));q.addEventListener('change',()=>updateHistoryCount(q));new MutationObserver(()=>updateHistoryCount(q)).observe(q,{childList:true,subtree:true});updateHistoryCount(q)}
new MutationObserver(()=>{init();initStepper();initHistoryCount();restrictAdminControls()}).observe(document.body,{childList:true,subtree:true});setTimeout(()=>{init();initStepper();initHistoryCount();restrictAdminControls()},300);

const currentQueueFilters={article:'',market:'ALL',status:'ALL'};
function applyCurrentQueueFilters(){const queue=document.querySelector('.queue.current-queue');if(!queue)return;const article=currentQueueFilters.article.trim().toUpperCase();let total=0;queue.querySelectorAll('.table .tr:not(.th)').forEach(row=>{const rowArticle=(row.children[0]?.querySelector('b')?.textContent||row.children[0]?.textContent||'').toUpperCase(),market=(row.children[1]?.textContent||'').trim(),status=(row.children[3]?.textContent||'').trim();const visible=(!article||rowArticle.includes(article))&&(currentQueueFilters.market==='ALL'||market===currentQueueFilters.market)&&(currentQueueFilters.status==='ALL'||status===currentQueueFilters.status);row.style.display=visible?'':'none';if(visible)total+=Number.parseInt((row.children[2]?.textContent||'').replace(/\s/g,''),10)||0});const count=queue.querySelector('.queue-count'),value=`${total} шт.`;if(count&&count.textContent!==value)count.textContent=value}
function syncCurrentQueueStickyOffset(){const queue=document.querySelector('.queue.current-queue'),head=queue?.querySelector('.queue-head');if(queue&&head)queue.style.setProperty('--current-queue-head-height',`${head.getBoundingClientRect().height}px`)}
function initCurrentQueue(){const queue=document.querySelector('.queue.current-queue'),header=queue?.querySelector('.table .tr.th');if(!queue||!header)return;if(!header.dataset.filters){header.innerHTML='<span><input class="queue-header-article" data-current-filter="article" aria-label="Поиск по артикулу" placeholder="Поиск по артикулу"></span><span><select data-current-filter="market" aria-label="Направление"><option value="ALL">Все направления</option><option value="WB">WB</option><option value="OZON">OZON</option></select></span><span>Кол-во</span><span><select data-current-filter="status" aria-label="Статус"><option value="ALL">Все статусы</option><option>Ожидает</option><option>В печати</option><option>Забрано</option><option>Напечатано</option><option>Ошибка</option></select></span><span>Время</span>';header.dataset.filters='1'}if(!header.dataset.bound){header.dataset.bound='1';header.querySelectorAll('[data-current-filter]').forEach(field=>{const key=field.dataset.currentFilter;field.value=currentQueueFilters[key]||(key==='article'?'':'ALL');const update=()=>{currentQueueFilters[key]=field.value;applyCurrentQueueFilters()};field.addEventListener('input',update);field.addEventListener('change',update)})}syncCurrentQueueStickyOffset();applyCurrentQueueFilters()}
window.addEventListener('resize',syncCurrentQueueStickyOffset);
new MutationObserver(initCurrentQueue).observe(document.body,{childList:true,subtree:true});setTimeout(initCurrentQueue,400);
